# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_demo.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_demo.ipynb 3
def say_hello(to):
    "say hello to someone"
    return f"Hello, {to}!"

# %% ../nbs/00_demo.ipynb 8
def foo(): pass
